// Code generated by protoc-gen-go. DO NOT EDIT.
// source: person.proto

package main

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TrainingItem struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Weight               uint32   `protobuf:"varint,2,opt,name=weight,proto3" json:"weight,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TrainingItem) Reset()         { *m = TrainingItem{} }
func (m *TrainingItem) String() string { return proto.CompactTextString(m) }
func (*TrainingItem) ProtoMessage()    {}
func (*TrainingItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c9e10cf24b1156d, []int{0}
}

func (m *TrainingItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrainingItem.Unmarshal(m, b)
}
func (m *TrainingItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrainingItem.Marshal(b, m, deterministic)
}
func (m *TrainingItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrainingItem.Merge(m, src)
}
func (m *TrainingItem) XXX_Size() int {
	return xxx_messageInfo_TrainingItem.Size(m)
}
func (m *TrainingItem) XXX_DiscardUnknown() {
	xxx_messageInfo_TrainingItem.DiscardUnknown(m)
}

var xxx_messageInfo_TrainingItem proto.InternalMessageInfo

func (m *TrainingItem) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *TrainingItem) GetWeight() uint32 {
	if m != nil {
		return m.Weight
	}
	return 0
}

type Person struct {
	Name                 string          `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Age                  uint32          `protobuf:"varint,2,opt,name=age,proto3" json:"age,omitempty"`
	TrainingItems        []*TrainingItem `protobuf:"bytes,3,rep,name=trainingItems,proto3" json:"trainingItems,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Person) Reset()         { *m = Person{} }
func (m *Person) String() string { return proto.CompactTextString(m) }
func (*Person) ProtoMessage()    {}
func (*Person) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c9e10cf24b1156d, []int{1}
}

func (m *Person) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Person.Unmarshal(m, b)
}
func (m *Person) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Person.Marshal(b, m, deterministic)
}
func (m *Person) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Person.Merge(m, src)
}
func (m *Person) XXX_Size() int {
	return xxx_messageInfo_Person.Size(m)
}
func (m *Person) XXX_DiscardUnknown() {
	xxx_messageInfo_Person.DiscardUnknown(m)
}

var xxx_messageInfo_Person proto.InternalMessageInfo

func (m *Person) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Person) GetAge() uint32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *Person) GetTrainingItems() []*TrainingItem {
	if m != nil {
		return m.TrainingItems
	}
	return nil
}

func init() {
	proto.RegisterType((*TrainingItem)(nil), "main.TrainingItem")
	proto.RegisterType((*Person)(nil), "main.Person")
}

func init() { proto.RegisterFile("person.proto", fileDescriptor_4c9e10cf24b1156d) }

var fileDescriptor_4c9e10cf24b1156d = []byte{
	// 146 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0x48, 0x2d, 0x2a,
	0xce, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xc9, 0x4d, 0xcc, 0xcc, 0x53, 0xb2,
	0xe2, 0xe2, 0x09, 0x29, 0x4a, 0xcc, 0xcc, 0xcb, 0xcc, 0x4b, 0xf7, 0x2c, 0x49, 0xcd, 0x15, 0x12,
	0xe2, 0x62, 0xc9, 0x4b, 0xcc, 0x4d, 0x95, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x02, 0xb3, 0x85,
	0xc4, 0xb8, 0xd8, 0xca, 0x53, 0x33, 0xd3, 0x33, 0x4a, 0x24, 0x98, 0x14, 0x18, 0x35, 0x78, 0x83,
	0xa0, 0x3c, 0xa5, 0x0c, 0x2e, 0xb6, 0x00, 0xb0, 0x89, 0x58, 0x75, 0x09, 0x70, 0x31, 0x27, 0xa6,
	0xa7, 0x42, 0xb5, 0x80, 0x98, 0x42, 0x16, 0x5c, 0xbc, 0x25, 0x48, 0x76, 0x15, 0x4b, 0x30, 0x2b,
	0x30, 0x6b, 0x70, 0x1b, 0x09, 0xe9, 0x81, 0x5c, 0xa2, 0x87, 0xec, 0x8c, 0x20, 0x54, 0x85, 0x49,
	0x6c, 0x60, 0x27, 0x1b, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0xc1, 0xcf, 0x45, 0x1a, 0xc2, 0x00,
	0x00, 0x00,
}
